// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/SteepTaq/avito-backend-internship-2025/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BulkUpdatePRReviewers provides a mock function with given fields: ctx, prReviewers
func (_m *MockRepository) BulkUpdatePRReviewers(ctx context.Context, prReviewers map[string][]string) error {
	ret := _m.Called(ctx, prReviewers)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdatePRReviewers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string][]string) error); ok {
		r0 = rf(ctx, prReviewers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_BulkUpdatePRReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdatePRReviewers'
type MockRepository_BulkUpdatePRReviewers_Call struct {
	*mock.Call
}

// BulkUpdatePRReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prReviewers map[string][]string
func (_e *MockRepository_Expecter) BulkUpdatePRReviewers(ctx interface{}, prReviewers interface{}) *MockRepository_BulkUpdatePRReviewers_Call {
	return &MockRepository_BulkUpdatePRReviewers_Call{Call: _e.mock.On("BulkUpdatePRReviewers", ctx, prReviewers)}
}

func (_c *MockRepository_BulkUpdatePRReviewers_Call) Run(run func(ctx context.Context, prReviewers map[string][]string)) *MockRepository_BulkUpdatePRReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string][]string))
	})
	return _c
}

func (_c *MockRepository_BulkUpdatePRReviewers_Call) Return(_a0 error) *MockRepository_BulkUpdatePRReviewers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_BulkUpdatePRReviewers_Call) RunAndReturn(run func(context.Context, map[string][]string) error) *MockRepository_BulkUpdatePRReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePR provides a mock function with given fields: ctx, pr
func (_m *MockRepository) CreatePR(ctx context.Context, pr *models.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockRepository_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *models.PullRequest
func (_e *MockRepository_Expecter) CreatePR(ctx interface{}, pr interface{}) *MockRepository_CreatePR_Call {
	return &MockRepository_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, pr)}
}

func (_c *MockRepository_CreatePR_Call) Run(run func(ctx context.Context, pr *models.PullRequest)) *MockRepository_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PullRequest))
	})
	return _c
}

func (_c *MockRepository_CreatePR_Call) Return(_a0 error) *MockRepository_CreatePR_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreatePR_Call) RunAndReturn(run func(context.Context, *models.PullRequest) error) *MockRepository_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, team
func (_m *MockRepository) CreateTeam(ctx context.Context, team *models.Team) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockRepository_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Team
func (_e *MockRepository_Expecter) CreateTeam(ctx interface{}, team interface{}) *MockRepository_CreateTeam_Call {
	return &MockRepository_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, team)}
}

func (_c *MockRepository_CreateTeam_Call) Run(run func(ctx context.Context, team *models.Team)) *MockRepository_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Team))
	})
	return _c
}

func (_c *MockRepository_CreateTeam_Call) Return(_a0 error) *MockRepository_CreateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateTeam_Call) RunAndReturn(run func(context.Context, *models.Team) error) *MockRepository_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateUsersByTeam provides a mock function with given fields: ctx, teamName, userIDs
func (_m *MockRepository) DeactivateUsersByTeam(ctx context.Context, teamName string, userIDs []string) ([]string, error) {
	ret := _m.Called(ctx, teamName, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUsersByTeam")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, error)); ok {
		return rf(ctx, teamName, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = rf(ctx, teamName, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, teamName, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DeactivateUsersByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateUsersByTeam'
type MockRepository_DeactivateUsersByTeam_Call struct {
	*mock.Call
}

// DeactivateUsersByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - userIDs []string
func (_e *MockRepository_Expecter) DeactivateUsersByTeam(ctx interface{}, teamName interface{}, userIDs interface{}) *MockRepository_DeactivateUsersByTeam_Call {
	return &MockRepository_DeactivateUsersByTeam_Call{Call: _e.mock.On("DeactivateUsersByTeam", ctx, teamName, userIDs)}
}

func (_c *MockRepository_DeactivateUsersByTeam_Call) Run(run func(ctx context.Context, teamName string, userIDs []string)) *MockRepository_DeactivateUsersByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockRepository_DeactivateUsersByTeam_Call) Return(_a0 []string, _a1 error) *MockRepository_DeactivateUsersByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DeactivateUsersByTeam_Call) RunAndReturn(run func(context.Context, string, []string) ([]string, error)) *MockRepository_DeactivateUsersByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveUsersByTeam provides a mock function with given fields: ctx, teamName, excludeUserID
func (_m *MockRepository) GetActiveUsersByTeam(ctx context.Context, teamName string, excludeUserID string) ([]*models.User, error) {
	ret := _m.Called(ctx, teamName, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveUsersByTeam")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*models.User, error)); ok {
		return rf(ctx, teamName, excludeUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*models.User); ok {
		r0 = rf(ctx, teamName, excludeUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, teamName, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetActiveUsersByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveUsersByTeam'
type MockRepository_GetActiveUsersByTeam_Call struct {
	*mock.Call
}

// GetActiveUsersByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - excludeUserID string
func (_e *MockRepository_Expecter) GetActiveUsersByTeam(ctx interface{}, teamName interface{}, excludeUserID interface{}) *MockRepository_GetActiveUsersByTeam_Call {
	return &MockRepository_GetActiveUsersByTeam_Call{Call: _e.mock.On("GetActiveUsersByTeam", ctx, teamName, excludeUserID)}
}

func (_c *MockRepository_GetActiveUsersByTeam_Call) Run(run func(ctx context.Context, teamName string, excludeUserID string)) *MockRepository_GetActiveUsersByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetActiveUsersByTeam_Call) Return(_a0 []*models.User, _a1 error) *MockRepository_GetActiveUsersByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetActiveUsersByTeam_Call) RunAndReturn(run func(context.Context, string, string) ([]*models.User, error)) *MockRepository_GetActiveUsersByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenPRsByReviewers provides a mock function with given fields: ctx, reviewerIDs
func (_m *MockRepository) GetOpenPRsByReviewers(ctx context.Context, reviewerIDs []string) ([]*models.PullRequest, error) {
	ret := _m.Called(ctx, reviewerIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenPRsByReviewers")
	}

	var r0 []*models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*models.PullRequest, error)); ok {
		return rf(ctx, reviewerIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*models.PullRequest); ok {
		r0 = rf(ctx, reviewerIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, reviewerIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetOpenPRsByReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenPRsByReviewers'
type MockRepository_GetOpenPRsByReviewers_Call struct {
	*mock.Call
}

// GetOpenPRsByReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerIDs []string
func (_e *MockRepository_Expecter) GetOpenPRsByReviewers(ctx interface{}, reviewerIDs interface{}) *MockRepository_GetOpenPRsByReviewers_Call {
	return &MockRepository_GetOpenPRsByReviewers_Call{Call: _e.mock.On("GetOpenPRsByReviewers", ctx, reviewerIDs)}
}

func (_c *MockRepository_GetOpenPRsByReviewers_Call) Run(run func(ctx context.Context, reviewerIDs []string)) *MockRepository_GetOpenPRsByReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRepository_GetOpenPRsByReviewers_Call) Return(_a0 []*models.PullRequest, _a1 error) *MockRepository_GetOpenPRsByReviewers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetOpenPRsByReviewers_Call) RunAndReturn(run func(context.Context, []string) ([]*models.PullRequest, error)) *MockRepository_GetOpenPRsByReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRByID provides a mock function with given fields: ctx, prID
func (_m *MockRepository) GetPRByID(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRByID")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPRByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRByID'
type MockRepository_GetPRByID_Call struct {
	*mock.Call
}

// GetPRByID is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockRepository_Expecter) GetPRByID(ctx interface{}, prID interface{}) *MockRepository_GetPRByID_Call {
	return &MockRepository_GetPRByID_Call{Call: _e.mock.On("GetPRByID", ctx, prID)}
}

func (_c *MockRepository_GetPRByID_Call) Run(run func(ctx context.Context, prID string)) *MockRepository_GetPRByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetPRByID_Call) Return(_a0 *models.PullRequest, _a1 error) *MockRepository_GetPRByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPRByID_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *MockRepository_GetPRByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRsByReviewer provides a mock function with given fields: ctx, reviewerID
func (_m *MockRepository) GetPRsByReviewer(ctx context.Context, reviewerID string) ([]*models.PullRequest, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRsByReviewer")
	}

	var r0 []*models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PullRequest, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PullRequest); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPRsByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRsByReviewer'
type MockRepository_GetPRsByReviewer_Call struct {
	*mock.Call
}

// GetPRsByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID string
func (_e *MockRepository_Expecter) GetPRsByReviewer(ctx interface{}, reviewerID interface{}) *MockRepository_GetPRsByReviewer_Call {
	return &MockRepository_GetPRsByReviewer_Call{Call: _e.mock.On("GetPRsByReviewer", ctx, reviewerID)}
}

func (_c *MockRepository_GetPRsByReviewer_Call) Run(run func(ctx context.Context, reviewerID string)) *MockRepository_GetPRsByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetPRsByReviewer_Call) Return(_a0 []*models.PullRequest, _a1 error) *MockRepository_GetPRsByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPRsByReviewer_Call) RunAndReturn(run func(context.Context, string) ([]*models.PullRequest, error)) *MockRepository_GetPRsByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockRepository) GetStats(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetStats(ctx interface{}) *MockRepository_GetStats_Call {
	return &MockRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockRepository_GetStats_Call) Run(run func(ctx context.Context)) *MockRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_GetStats_Call) Return(_a0 map[string]interface{}, _a1 error) *MockRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetStats_Call) RunAndReturn(run func(context.Context) (map[string]interface{}, error)) *MockRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, teamName
func (_m *MockRepository) GetTeam(ctx context.Context, teamName string) (*models.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockRepository_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockRepository_Expecter) GetTeam(ctx interface{}, teamName interface{}) *MockRepository_GetTeam_Call {
	return &MockRepository_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamName)}
}

func (_c *MockRepository_GetTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockRepository_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetTeam_Call) Return(_a0 *models.Team, _a1 error) *MockRepository_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *MockRepository_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetUserByID(ctx context.Context, userID string) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) GetUserByID(ctx interface{}, userID interface{}) *MockRepository_GetUserByID_Call {
	return &MockRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByTeam provides a mock function with given fields: ctx, teamName
func (_m *MockRepository) GetUsersByTeam(ctx context.Context, teamName string) ([]*models.User, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByTeam")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.User, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.User); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUsersByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByTeam'
type MockRepository_GetUsersByTeam_Call struct {
	*mock.Call
}

// GetUsersByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockRepository_Expecter) GetUsersByTeam(ctx interface{}, teamName interface{}) *MockRepository_GetUsersByTeam_Call {
	return &MockRepository_GetUsersByTeam_Call{Call: _e.mock.On("GetUsersByTeam", ctx, teamName)}
}

func (_c *MockRepository_GetUsersByTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockRepository_GetUsersByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUsersByTeam_Call) Return(_a0 []*models.User, _a1 error) *MockRepository_GetUsersByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUsersByTeam_Call) RunAndReturn(run func(context.Context, string) ([]*models.User, error)) *MockRepository_GetUsersByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// PRExists provides a mock function with given fields: ctx, prID
func (_m *MockRepository) PRExists(ctx context.Context, prID string) (bool, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for PRExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_PRExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PRExists'
type MockRepository_PRExists_Call struct {
	*mock.Call
}

// PRExists is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockRepository_Expecter) PRExists(ctx interface{}, prID interface{}) *MockRepository_PRExists_Call {
	return &MockRepository_PRExists_Call{Call: _e.mock.On("PRExists", ctx, prID)}
}

func (_c *MockRepository_PRExists_Call) Run(run func(ctx context.Context, prID string)) *MockRepository_PRExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_PRExists_Call) Return(_a0 bool, _a1 error) *MockRepository_PRExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_PRExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepository_PRExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserActive provides a mock function with given fields: ctx, userID, isActive
func (_m *MockRepository) SetUserActive(ctx context.Context, userID string, isActive bool) error {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetUserActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetUserActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserActive'
type MockRepository_SetUserActive_Call struct {
	*mock.Call
}

// SetUserActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockRepository_Expecter) SetUserActive(ctx interface{}, userID interface{}, isActive interface{}) *MockRepository_SetUserActive_Call {
	return &MockRepository_SetUserActive_Call{Call: _e.mock.On("SetUserActive", ctx, userID, isActive)}
}

func (_c *MockRepository_SetUserActive_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockRepository_SetUserActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockRepository_SetUserActive_Call) Return(_a0 error) *MockRepository_SetUserActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetUserActive_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockRepository_SetUserActive_Call {
	_c.Call.Return(run)
	return _c
}

// TeamExists provides a mock function with given fields: ctx, teamName
func (_m *MockRepository) TeamExists(ctx context.Context, teamName string) (bool, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for TeamExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, teamName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_TeamExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamExists'
type MockRepository_TeamExists_Call struct {
	*mock.Call
}

// TeamExists is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockRepository_Expecter) TeamExists(ctx interface{}, teamName interface{}) *MockRepository_TeamExists_Call {
	return &MockRepository_TeamExists_Call{Call: _e.mock.On("TeamExists", ctx, teamName)}
}

func (_c *MockRepository_TeamExists_Call) Run(run func(ctx context.Context, teamName string)) *MockRepository_TeamExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_TeamExists_Call) Return(_a0 bool, _a1 error) *MockRepository_TeamExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_TeamExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepository_TeamExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePRReviewers provides a mock function with given fields: ctx, prID, reviewers
func (_m *MockRepository) UpdatePRReviewers(ctx context.Context, prID string, reviewers []string) error {
	ret := _m.Called(ctx, prID, reviewers)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePRReviewers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, prID, reviewers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdatePRReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePRReviewers'
type MockRepository_UpdatePRReviewers_Call struct {
	*mock.Call
}

// UpdatePRReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - reviewers []string
func (_e *MockRepository_Expecter) UpdatePRReviewers(ctx interface{}, prID interface{}, reviewers interface{}) *MockRepository_UpdatePRReviewers_Call {
	return &MockRepository_UpdatePRReviewers_Call{Call: _e.mock.On("UpdatePRReviewers", ctx, prID, reviewers)}
}

func (_c *MockRepository_UpdatePRReviewers_Call) Run(run func(ctx context.Context, prID string, reviewers []string)) *MockRepository_UpdatePRReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockRepository_UpdatePRReviewers_Call) Return(_a0 error) *MockRepository_UpdatePRReviewers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdatePRReviewers_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockRepository_UpdatePRReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePRStatus provides a mock function with given fields: ctx, prID, status
func (_m *MockRepository) UpdatePRStatus(ctx context.Context, prID string, status models.PRStatus) error {
	ret := _m.Called(ctx, prID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePRStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.PRStatus) error); ok {
		r0 = rf(ctx, prID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdatePRStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePRStatus'
type MockRepository_UpdatePRStatus_Call struct {
	*mock.Call
}

// UpdatePRStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - status models.PRStatus
func (_e *MockRepository_Expecter) UpdatePRStatus(ctx interface{}, prID interface{}, status interface{}) *MockRepository_UpdatePRStatus_Call {
	return &MockRepository_UpdatePRStatus_Call{Call: _e.mock.On("UpdatePRStatus", ctx, prID, status)}
}

func (_c *MockRepository_UpdatePRStatus_Call) Run(run func(ctx context.Context, prID string, status models.PRStatus)) *MockRepository_UpdatePRStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.PRStatus))
	})
	return _c
}

func (_c *MockRepository_UpdatePRStatus_Call) Return(_a0 error) *MockRepository_UpdatePRStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdatePRStatus_Call) RunAndReturn(run func(context.Context, string, models.PRStatus) error) *MockRepository_UpdatePRStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePRStatusWithMergedAt provides a mock function with given fields: ctx, prID, status
func (_m *MockRepository) UpdatePRStatusWithMergedAt(ctx context.Context, prID string, status models.PRStatus) error {
	ret := _m.Called(ctx, prID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePRStatusWithMergedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.PRStatus) error); ok {
		r0 = rf(ctx, prID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdatePRStatusWithMergedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePRStatusWithMergedAt'
type MockRepository_UpdatePRStatusWithMergedAt_Call struct {
	*mock.Call
}

// UpdatePRStatusWithMergedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - status models.PRStatus
func (_e *MockRepository_Expecter) UpdatePRStatusWithMergedAt(ctx interface{}, prID interface{}, status interface{}) *MockRepository_UpdatePRStatusWithMergedAt_Call {
	return &MockRepository_UpdatePRStatusWithMergedAt_Call{Call: _e.mock.On("UpdatePRStatusWithMergedAt", ctx, prID, status)}
}

func (_c *MockRepository_UpdatePRStatusWithMergedAt_Call) Run(run func(ctx context.Context, prID string, status models.PRStatus)) *MockRepository_UpdatePRStatusWithMergedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.PRStatus))
	})
	return _c
}

func (_c *MockRepository_UpdatePRStatusWithMergedAt_Call) Return(_a0 error) *MockRepository_UpdatePRStatusWithMergedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdatePRStatusWithMergedAt_Call) RunAndReturn(run func(context.Context, string, models.PRStatus) error) *MockRepository_UpdatePRStatusWithMergedAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
