// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/SteepTaq/avito-backend-internship-2025/internal/models"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreatePR provides a mock function with given fields: ctx, prID, prName, authorID
func (_m *MockService) CreatePR(ctx context.Context, prID string, prName string, authorID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID, prName, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID, prName, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID, prName, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, prID, prName, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreatePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePR'
type MockService_CreatePR_Call struct {
	*mock.Call
}

// CreatePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - prName string
//   - authorID string
func (_e *MockService_Expecter) CreatePR(ctx interface{}, prID interface{}, prName interface{}, authorID interface{}) *MockService_CreatePR_Call {
	return &MockService_CreatePR_Call{Call: _e.mock.On("CreatePR", ctx, prID, prName, authorID)}
}

func (_c *MockService_CreatePR_Call) Run(run func(ctx context.Context, prID string, prName string, authorID string)) *MockService_CreatePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_CreatePR_Call) Return(_a0 *models.PullRequest, _a1 error) *MockService_CreatePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreatePR_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.PullRequest, error)) *MockService_CreatePR_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function with given fields: ctx, team
func (_m *MockService) CreateTeam(ctx context.Context, team *models.Team) (*models.Team, error) {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) (*models.Team, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) *models.Team); ok {
		r0 = rf(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Team) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockService_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team *models.Team
func (_e *MockService_Expecter) CreateTeam(ctx interface{}, team interface{}) *MockService_CreateTeam_Call {
	return &MockService_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, team)}
}

func (_c *MockService_CreateTeam_Call) Run(run func(ctx context.Context, team *models.Team)) *MockService_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Team))
	})
	return _c
}

func (_c *MockService_CreateTeam_Call) Return(_a0 *models.Team, _a1 error) *MockService_CreateTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateTeam_Call) RunAndReturn(run func(context.Context, *models.Team) (*models.Team, error)) *MockService_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateTeamUsers provides a mock function with given fields: ctx, teamName, userIDs
func (_m *MockService) DeactivateTeamUsers(ctx context.Context, teamName string, userIDs []string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, teamName, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateTeamUsers")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]interface{}, error)); ok {
		return rf(ctx, teamName, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) map[string]interface{}); ok {
		r0 = rf(ctx, teamName, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, teamName, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_DeactivateTeamUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateTeamUsers'
type MockService_DeactivateTeamUsers_Call struct {
	*mock.Call
}

// DeactivateTeamUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - userIDs []string
func (_e *MockService_Expecter) DeactivateTeamUsers(ctx interface{}, teamName interface{}, userIDs interface{}) *MockService_DeactivateTeamUsers_Call {
	return &MockService_DeactivateTeamUsers_Call{Call: _e.mock.On("DeactivateTeamUsers", ctx, teamName, userIDs)}
}

func (_c *MockService_DeactivateTeamUsers_Call) Run(run func(ctx context.Context, teamName string, userIDs []string)) *MockService_DeactivateTeamUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockService_DeactivateTeamUsers_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_DeactivateTeamUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_DeactivateTeamUsers_Call) RunAndReturn(run func(context.Context, string, []string) (map[string]interface{}, error)) *MockService_DeactivateTeamUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPRsByReviewer provides a mock function with given fields: ctx, reviewerID
func (_m *MockService) GetPRsByReviewer(ctx context.Context, reviewerID string) ([]*models.PullRequestShort, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPRsByReviewer")
	}

	var r0 []*models.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PullRequestShort, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PullRequestShort); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetPRsByReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPRsByReviewer'
type MockService_GetPRsByReviewer_Call struct {
	*mock.Call
}

// GetPRsByReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID string
func (_e *MockService_Expecter) GetPRsByReviewer(ctx interface{}, reviewerID interface{}) *MockService_GetPRsByReviewer_Call {
	return &MockService_GetPRsByReviewer_Call{Call: _e.mock.On("GetPRsByReviewer", ctx, reviewerID)}
}

func (_c *MockService_GetPRsByReviewer_Call) Run(run func(ctx context.Context, reviewerID string)) *MockService_GetPRsByReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetPRsByReviewer_Call) Return(_a0 []*models.PullRequestShort, _a1 error) *MockService_GetPRsByReviewer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetPRsByReviewer_Call) RunAndReturn(run func(context.Context, string) ([]*models.PullRequestShort, error)) *MockService_GetPRsByReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockService) GetStats(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockService_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetStats(ctx interface{}) *MockService_GetStats_Call {
	return &MockService_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockService_GetStats_Call) Run(run func(ctx context.Context)) *MockService_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetStats_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetStats_Call) RunAndReturn(run func(context.Context) (map[string]interface{}, error)) *MockService_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: ctx, teamName
func (_m *MockService) GetTeam(ctx context.Context, teamName string) (*models.Team, error) {
	ret := _m.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Team, error)); ok {
		return rf(ctx, teamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockService_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockService_Expecter) GetTeam(ctx interface{}, teamName interface{}) *MockService_GetTeam_Call {
	return &MockService_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamName)}
}

func (_c *MockService_GetTeam_Call) Run(run func(ctx context.Context, teamName string)) *MockService_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetTeam_Call) Return(_a0 *models.Team, _a1 error) *MockService_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetTeam_Call) RunAndReturn(run func(context.Context, string) (*models.Team, error)) *MockService_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// MergePR provides a mock function with given fields: ctx, prID
func (_m *MockService) MergePR(ctx context.Context, prID string) (*models.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *models.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_MergePR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePR'
type MockService_MergePR_Call struct {
	*mock.Call
}

// MergePR is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
func (_e *MockService_Expecter) MergePR(ctx interface{}, prID interface{}) *MockService_MergePR_Call {
	return &MockService_MergePR_Call{Call: _e.mock.On("MergePR", ctx, prID)}
}

func (_c *MockService_MergePR_Call) Run(run func(ctx context.Context, prID string)) *MockService_MergePR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_MergePR_Call) Return(_a0 *models.PullRequest, _a1 error) *MockService_MergePR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_MergePR_Call) RunAndReturn(run func(context.Context, string) (*models.PullRequest, error)) *MockService_MergePR_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockService) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Ping(ctx interface{}) *MockService_Ping_Call {
	return &MockService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockService_Ping_Call) Run(run func(ctx context.Context)) *MockService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Ping_Call) Return(_a0 error) *MockService_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Ping_Call) RunAndReturn(run func(context.Context) error) *MockService_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldReviewerID
func (_m *MockService) ReassignReviewer(ctx context.Context, prID string, oldReviewerID string) (*models.PullRequest, string, error) {
	ret := _m.Called(ctx, prID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *models.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.PullRequest, string, error)); ok {
		return rf(ctx, prID, oldReviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.PullRequest); ok {
		r0 = rf(ctx, prID, oldReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, prID, oldReviewerID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, prID, oldReviewerID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_ReassignReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignReviewer'
type MockService_ReassignReviewer_Call struct {
	*mock.Call
}

// ReassignReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldReviewerID string
func (_e *MockService_Expecter) ReassignReviewer(ctx interface{}, prID interface{}, oldReviewerID interface{}) *MockService_ReassignReviewer_Call {
	return &MockService_ReassignReviewer_Call{Call: _e.mock.On("ReassignReviewer", ctx, prID, oldReviewerID)}
}

func (_c *MockService_ReassignReviewer_Call) Run(run func(ctx context.Context, prID string, oldReviewerID string)) *MockService_ReassignReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_ReassignReviewer_Call) Return(_a0 *models.PullRequest, _a1 string, _a2 error) *MockService_ReassignReviewer_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_ReassignReviewer_Call) RunAndReturn(run func(context.Context, string, string) (*models.PullRequest, string, error)) *MockService_ReassignReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserActive provides a mock function with given fields: ctx, userID, isActive
func (_m *MockService) SetUserActive(ctx context.Context, userID string, isActive bool) (*models.User, error) {
	ret := _m.Called(ctx, userID, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetUserActive")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*models.User, error)); ok {
		return rf(ctx, userID, isActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *models.User); ok {
		r0 = rf(ctx, userID, isActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, isActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SetUserActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserActive'
type MockService_SetUserActive_Call struct {
	*mock.Call
}

// SetUserActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - isActive bool
func (_e *MockService_Expecter) SetUserActive(ctx interface{}, userID interface{}, isActive interface{}) *MockService_SetUserActive_Call {
	return &MockService_SetUserActive_Call{Call: _e.mock.On("SetUserActive", ctx, userID, isActive)}
}

func (_c *MockService_SetUserActive_Call) Run(run func(ctx context.Context, userID string, isActive bool)) *MockService_SetUserActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockService_SetUserActive_Call) Return(_a0 *models.User, _a1 error) *MockService_SetUserActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SetUserActive_Call) RunAndReturn(run func(context.Context, string, bool) (*models.User, error)) *MockService_SetUserActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
